services:
  discovery:
    build:
      context: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  config:
    build:
      context: ./config-server
    container_name: config
    ports:
      - "8888:8888"
    networks:
      - microservice-net
    depends_on:
      discovery:
        condition: service_healthy
    restart: on-failure

networks:
  microservice-net:


#  swag:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: swag
#    ports:
#      - "8081:8081"
#    networks:
#      - microservice-net
#    depends_on:
#      - discovery
#      - config
#
#  swagger:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: swagger
#    ports:
#      - "8082:8082"
#    networks:
#      - microservice-net
#    depends_on:
#      - discovery
#      - config
#
#  swaggest:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: swaggest
#    ports:
#      - "8083:8083"
#    networks:
#      - microservice-net
#    depends_on:
#      - discovery
#      - config
